apiVersion: v1
kind: ConfigMap
metadata:
  name: hospital-config

data:
  APP_SETTINGS: config.DevelopmentConfig
  DATABASE_URL: postgresql://hospital:hospital123@postgres-service:5432/hospital_db
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_NAME: hospital_db
  DB_USER: hospital